version: 1.0.$(APPVEYOR_BUILD_NUMBER)
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(APPVEYOR_BUILD_VERSION)'
  assembly_file_version: '$(APPVEYOR_BUILD_VERSION)'
  assembly_informational_version: '$(APPVEYOR_BUILD_VERSION)'
environment:
  NuGetApiKey:
    secure: /0Z5Cw06AdhoTRWdDCY6lEf6mL6m2WzkA1KgiJnjwFfpHVgfdDMdqVHQPpnI1K6O
build:
  project: .\Source\$(APPVEYOR_PROJECT_NAME).sln
  verbosity: minimal
on_finish:
- cmd: .\Build\NuGet\PackageAndPush.cmd
